/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2014-11-28 16:01:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.sql.*;
import java.text.*;
import javax.naming.*;
import javax.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");

  request.setCharacterEncoding("Windows-31J");
  response.setCharacterEncoding("Windows-31J");

      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"Windows-31J\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Book On</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"css/jumbotron.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    ");

      String enable_pub_name = request.getParameter("enable_pub_name");
      String pub_name = request.getParameter("pub_name");
      String name = request.getParameter("name");
      String writer = request.getParameter("writer");
      String isbn = request.getParameter("isbn");
      String below_price = request.getParameter("below_price");
      String above_price = request.getParameter("above_price");
      String large_id = request.getParameter("large_id");
      String middle_id = request.getParameter("middle_id");
      String small_id = request.getParameter("small_id");
      String email = request.getParameter("email");
      String login_pass = request.getParameter("password");

      if((email != null || email != "") && (login_pass != null || login_pass != "")){
        Context context = new InitialContext();
        DataSource ds = (DataSource)context.lookup("java:comp/env/jdbc/bookon");
        Connection db6 = ds.getConnection();
        db6.setReadOnly(true);
        Statement objSql6=db6.createStatement();
        String login_query = ("SELECT * FROM user_data WHERE email = '" + email + "' AND password = HASHBYTES('SHA2_256', '" + login_pass + "')");
        ResultSet rs6=objSql6.executeQuery(login_query);

        if(rs6.next()){
                //セッションを一度破棄
                session.invalidate();
                //セッション再生成
                session = request.getSession();
                //セッションへ保存
                session.setAttribute("email", email);
                //画面遷移
                response.sendRedirect("./index.jsp");
            }
        rs6.close();
        objSql6.close();
        db6.close();
        }
    
      out.write("\r\n");
      out.write("    <div class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\" onClick=\"clearAll()\">Book On</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t    \t\t<li><a href=\"\">about</a></li>\r\n");
      out.write("\t\t    \t\t<li><a href=\"\">contact</a></li>\r\n");
      out.write("            <li><a href=\"\">");
      out.print( new Date() );
      out.write("</a></li>\r\n");
      out.write("\t\t      </ul>\r\n");
      out.write("          ");
if((session.getAttribute("login") == null) || !session.getAttribute("login").equals("true")){
      out.write("\r\n");
      out.write("          <form class=\"navbar-form navbar-right\" role=\"form\" method=\"post\" action=\"Authentication\">\r\n");
      out.write("          <div class=\"form-group ");
if (session.getAttribute("login") != null &&
      !session.getAttribute("login").equals("true")){
      out.write("has-error has-feedback");
}
      out.write("\">\r\n");
      out.write("          <input type=\"text\" name='email' placeholder=\"Email\" class=\"form-control\">\r\n");
      out.write("          ");
if (session.getAttribute("login") != null &&
              !session.getAttribute("login").equals("true")){
      out.write("\r\n");
      out.write("              <span class=\"glyphicon glyphicon-remove form-control-feedback\"></span>\r\n");
      out.write("              ");
}
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group ");
if (session.getAttribute("login") != null &&
      !session.getAttribute("login").equals("true")){
      out.write("has-error has-feedback");
}
      out.write("\">\r\n");
      out.write("            <input type=\"password\" name='pass' placeholder=\"Password\" class=\"form-control\">\r\n");
      out.write("            ");
if (session.getAttribute("login") != null &&
              !session.getAttribute("login").equals("true")){
      out.write("\r\n");
      out.write("              <span class=\"glyphicon glyphicon-remove form-control-feedback\"></span>\r\n");
      out.write("              ");
}
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <button type=\"submit\" class=\"btn btn-success\">ログイン</button>\r\n");
      out.write("          <!-- Button trigger modal -->\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-success\" data-toggle=\"modal\" data-target=\"#myModal\">登録\r\n");
      out.write("          </button>\r\n");
      out.write("          </form>\r\n");
      out.write("          ");
}else{
      out.write("\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("              <li><a href=\"#\">");
      out.print(session.getAttribute("email"));
      out.write("</a></li>\r\n");
      out.write("              <li>\r\n");
      out.write("                  <form class=\"navbar-form navbar-right\" role=\"form\" method=\"post\" action=\"SignOut\">\r\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-success\">ログアウト</button>\r\n");
      out.write("                  </form>\r\n");
      out.write("              </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          ");
}
      out.write("\r\n");
      out.write("        </div><!--/.navbar-collapse -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog\">\r\n");
      out.write("        <form class=\"form-horizontal register_form\" method=\"POST\" name=\"register_form\" role=\"form\" action=\"RegisterTransaction\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <button type=\"button\" class=\"close\" data-dismiss=\"modal\"><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\">Close</span></button>\r\n");
      out.write("              <h4 class=\"modal-title\" id=\"myModalLabel\">ユーザー登録</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <label for=\"register_id\" class=\"col-md-4 control-label\">ID</label>\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"register_id\" maxlength=\"4\" placeholder=\"ID\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <label for=\"register_last_name\" class=\"col-md-4 control-label\">名前</label>\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"register_last_name\" placeholder=\"姓\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"register_first_name\" placeholder=\"名\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <label for=\"register_email\" class=\"col-md-4 control-label\">メールアドレス</label>\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"register_email\" maxlength=\"100\" placeholder=\"Email\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <label for=\"register_password\" class=\"col-md-4 control-label\">パスワード</label>\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" name=\"register_password\" placeholder=\"Password\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <label for=\"confirm_register_password\" class=\"col-md-4 control-label\">パスワード再入力</label>\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" name=\"confirm_register_password\" placeholder=\"Password\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("              <button type=\"submit\" class=\"btn btn-success\" name=\"register\">登録</button>\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">閉じる</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <form class=\"form search_form\" name=\"search_form\" role=\"form\" action=\"#\">\r\n");
      out.write("          <div class=\"col-sm-2\" style=\"background:white;\">\r\n");
      out.write("            <div class=\"btn-group-vertical btn-block\" data-toggle=\"buttons\">\r\n");
      out.write("              <label class=\"btn btn-primary\">\r\n");
      out.write("                <input type=\"radio\" autocomplete=\"off\">大分類\r\n");
      out.write("              </label>\r\n");
      out.write("              ");

              Context context = new InitialContext();
              DataSource ds = (DataSource)context.lookup("java:comp/env/jdbc/bookon");
              Connection db = ds.getConnection();
              db.setReadOnly(true);
              Statement objSql=db.createStatement();
              ResultSet rs=objSql.executeQuery("SELECT DISTINCT large_id, large FROM group_master ORDER BY large_id");
              while(rs.next()){
              
      out.write("\r\n");
      out.write("                <label ");
if(large_id != null){if(large_id.equals(rs.getString("large_id"))){
      out.write("class=\"btn btn-default active\"");
}else{
      out.write("class=\"btn btn-default\"");
}}else{
      out.write("class=\"btn btn-default\"");
}
      out.write(">\r\n");
      out.write("                  <input type=\"radio\" name=\"large_id\" value ='");
      out.print(rs.getString("large_id"));
      out.write("' autocomplete=\"off\" ");
if(large_id != null){if(large_id.equals(rs.getString("large_id"))){
      out.write("checked");
}}
      out.write(" onChange=\"wrapperSubmit(this)\">");
      out.print(rs.getString("large"));
      out.write("\r\n");
      out.write("                </label>\r\n");
      out.write("              ");

              }
              rs.close();
              objSql.close();
              
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm-2\" style=\"background:white;\">\r\n");
      out.write("            <div class=\"btn-group-vertical btn-block\" data-toggle=\"buttons\">\r\n");
      out.write("              <label class=\"btn btn-success\">\r\n");
      out.write("                <input type=\"radio\" autocomplete=\"off\">中分類\r\n");
      out.write("              </label>\r\n");
      out.write("              ");

              Statement objSql2=db.createStatement();
              String middle_query = "SELECT DISTINCT middle_id, middle FROM group_master WHERE large_id = ";
              if(large_id != null)
              {
                middle_query += large_id;
              }
              else
              {
                middle_query += "1";
              }
              ResultSet rs2=objSql2.executeQuery(middle_query);
              while(rs2.next()){
              
      out.write("\r\n");
      out.write("                <label ");
if(middle_id != null){if(middle_id.equals(rs2.getString("middle_id"))){
      out.write("class=\"btn btn-default active\"");
}else{
      out.write("class=\"btn btn-default\"");
}}else{
      out.write("class=\"btn btn-default\"");
}
      out.write(">\r\n");
      out.write("                  <input type=\"radio\" name=\"middle_id\" value ='");
      out.print(rs2.getString("middle_id"));
      out.write("' autocomplete=\"off\" ");
if(middle_id != null){if(middle_id.equals(rs2.getString("middle_id"))){
      out.write("checked");
}}
      out.write(" onChange=\"wrapperSubmit(this)\">");
      out.print(rs2.getString("middle"));
      out.write("\r\n");
      out.write("                </label>\r\n");
      out.write("              ");

              }
              rs2.close();
              objSql2.close();
              
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm-2\" style=\"background:white;\">\r\n");
      out.write("            <div class=\"btn-group-vertical btn-block\" data-toggle=\"buttons\">\r\n");
      out.write("              <label class=\"btn btn-danger\">\r\n");
      out.write("                <input type=\"radio\" autocomplete=\"off\">小分類\r\n");
      out.write("              </label>\r\n");
      out.write("              ");

                Statement objSql3=db.createStatement();
                String small_query = "SELECT DISTINCT small_id, small FROM group_master WHERE large_id = ";
                if(large_id != null)
                {
                  small_query += large_id;
                }
                else
                {
                  small_query += "1";
                }
                if(middle_id != null)
                {
                  small_query += (" AND middle_id = " + middle_id);
                }
                else
                {
                  small_query += " AND middle_id = 1";
                }
                ResultSet rs3=objSql3.executeQuery(small_query);
                while(rs3.next()){
              
      out.write("\r\n");
      out.write("                <label ");
if(small_id != null){if(small_id.equals(rs3.getString("small_id"))){
      out.write("class=\"btn btn-default active\"");
}else{
      out.write("class=\"btn btn-default\"");
}}else{
      out.write("class=\"btn btn-default\"");
}
      out.write(">\r\n");
      out.write("                  <input type=\"radio\" name=\"small_id\" value ='");
      out.print(rs3.getString("small_id"));
      out.write("' autocomplete=\"off\" ");
if(small_id != null){if(small_id.equals(rs3.getString("small_id"))){
      out.write("checked");
}}
      out.write(" onChange=\"wrapperSubmit(this)\">");
      out.print(rs3.getString("small"));
      out.write("\r\n");
      out.write("                </label>\r\n");
      out.write("              ");

              }
              rs3.close();
              objSql3.close();
              
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm-2\" style=\"background:white;\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <div class=\"checkbox\">\r\n");
      out.write("                <label>\r\n");
      out.write("                  <input type=\"checkbox\" name=\"enable_pub_name\" value=\"enable\" ");
if (enable_pub_name != null){
      out.write("checked");
}
      out.write(">\r\n");
      out.write("                  出版社\r\n");
      out.write("                </label>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <select id=\"pub_name\" name=\"pub_name\" size =\"14\" class=\"form-control\">\r\n");
      out.write("              ");

                Statement objSql4=db.createStatement();
                ResultSet rs4=objSql4.executeQuery("SELECT DISTINCT pub_name FROM books_data, pub_master WHERE books_data.pub_id = pub_master.pub_id");
                while(rs4.next()){
              
      out.write("\r\n");
      out.write("              <option ");
if(pub_name != null){if(pub_name.equals(rs4.getString("pub_name"))){
      out.write("selected");
}}
      out.write('>');
      out.print(rs4.getString("pub_name"));
      out.write("</option>\r\n");
      out.write("              ");

              }
              rs4.close();
              objSql4.close();
              
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm-2\" style=\"background:white;\">\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-book\"></span></div>\r\n");
      out.write("                    <input class=\"form-control\" type=\"text\" name=\"name\" value='");
if (name != null){
      out.print(name);
}
      out.write("' placeholder=\"書籍名\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                    <input class=\"form-control\" type=\"text\" name=\"writer\" value='");
if (writer != null){
      out.print(writer);
}
      out.write("' placeholder=\"著者\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-barcode\"></span></div>\r\n");
      out.write("                    <input class=\"form-control\" type=\"text\" name=\"isbn\" value='");
if (isbn != null){
      out.print(isbn);
}
      out.write("' placeholder=\"ISBN\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-usd\"></span></div>\r\n");
      out.write("                    <input class=\"form-control\" type=\"text\" name=\"below_price\" value='");
if (below_price != null){
      out.print(below_price);
}
      out.write("' placeholder=\"価格\">\r\n");
      out.write("                  <div class=\"input-group-addon\">以下</span></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-usd\"></span></div>\r\n");
      out.write("                    <input class=\"form-control\" type=\"text\" name=\"above_price\" value='");
if (above_price != null){
      out.print(above_price);
}
      out.write("' placeholder=\"価格\">\r\n");
      out.write("                  <div class=\"input-group-addon\">以上</span></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\">検索</button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <div class=\"col-sm-2\" style=\"background:white;\">\r\n");
      out.write("          <form class=\"form\" name=\"item_state_form\" role=\"form\" action=\"./return.jsp\">\r\n");
      out.write("            <div class=\"btn-group-vertical btn-block\">\r\n");
      out.write("              <button type=\"submit\" class=\"btn btn-default btn-block\">");
if((session.getAttribute("login") != null) && session.getAttribute("login").equals("true")){
      out.print(session.getAttribute("last_name"));
      out.write(' ');
      out.print(session.getAttribute("first_name"));
      out.write(' ');
      out.write('さ');
      out.write('ん');
}else{
      out.write('全');
      out.write('体');
}
      out.write("</button>\r\n");
      out.write("              ");

              Statement objSql7=db.createStatement();
              String countQuery = "SELECT COUNT(*) AS number FROM item_state WHERE return_date IS NULL";
              if((session.getAttribute("login") != null) && session.getAttribute("login").equals("true"))
                {
                  countQuery += " AND id = '" + session.getAttribute("id") + "'";
                }
              ResultSet rs7=objSql7.executeQuery(countQuery);
              while(rs7.next()){
              
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-default btn-block\">貸出中書籍 <span class=\"badge pull-right\">");
      out.print(rs7.getInt("number"));
      out.write("</span></button>\r\n");
      out.write("              ");

              }
              rs7.close();
              objSql7.close();

              Statement objSql8=db.createStatement();
              String overdueQuery = "SELECT COUNT(*) AS number FROM item_state WHERE return_date IS NULL AND estimate_return_date < DATEDIFF(day, 1, GETDATE())";
              if((session.getAttribute("login") != null) && session.getAttribute("login").equals("true"))
                {
                  overdueQuery += " AND id = '" + session.getAttribute("id") + "'";
                }
              ResultSet rs8=objSql8.executeQuery(overdueQuery);
              while(rs8.next()){
              
      out.write("\r\n");
      out.write("              <button type=\"submit\" class=\"btn btn-default btn-block\">貸出期限超過 <span class=\"badge pull-right\">");
      out.print(rs8.getInt("number"));
      out.write("</span></button>\r\n");
      out.write("              ");

              }
              
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"panel panel-default\">\r\n");
      out.write("        <!-- Default panel contents -->\r\n");
      out.write("        <form class=\"form\" name=\"book_table\" role=\"form\" action=\"LendTransaction\">\r\n");
      out.write("          <div class=\"panel-heading\">検索結果\r\n");
      out.write("            <div class=\"form-group pull-right\">\r\n");
      out.write("              <button type=\"button\" name=\"pdf\" class=\"btn btn-danger\" onClick =\"createPDF()\">PDF</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Table -->\r\n");
      out.write("          <table class=\"table\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <th>#</th>\r\n");
      out.write("              <th>書籍名</th>\r\n");
      out.write("              <th>著者</th>\r\n");
      out.write("              <th>出版社</th>\r\n");
      out.write("              <th>発行年</th>\r\n");
      out.write("              <th>ISBN</th>\r\n");
      out.write("              <th>価格</th>\r\n");
      out.write("              <th>貸出状況</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

            String query = "SELECT books_data.bk_id, bk_name, writer, pub_name, pub_date, isbn_no, price, state = CASE WHEN lend_date IS NOT NULL AND return_date IS NULL THEN 'false' ELSE 'true' END FROM books_data LEFT OUTER JOIN item_state ON books_data.bk_id = item_state.bk_id, pub_master WHERE pub_master.pub_id = books_data.pub_id";
            if((pub_name != "") && (enable_pub_name != null))
            {
              query += (" AND pub_name = '" + pub_name + "'");
            }
            if(name != null && name !="")
            {
              query += (" AND bk_name LIKE '%" + name + "%'");
            }
            if(writer != null && writer !="")
            {
              query += (" AND writer LIKE '%" + writer + "%'");
            }
            if(isbn != null && isbn !="")
            {
              query += (" AND isbn_no = '" + isbn + "'");
            }
            if(below_price != null && below_price !="")
            {
              query += (" AND price <= " + below_price);
            }
            if(above_price != null && above_price !="")
            {
              query += (" AND price >= " + above_price);
            }
            if(large_id != null && large_id !="")
            {
              query += (" AND books_data.bk_id LIKE '" + large_id + "%'");
            }
            if(middle_id != null && middle_id !="")
            {
              query += (" AND books_data.bk_id LIKE '_" + middle_id + "%'");
            }
            if(small_id != null && small_id !="")
            {
              query += (" AND books_data.bk_id LIKE '__" + small_id + "%'");
            }
              session.setAttribute("large_id", large_id);
              session.setAttribute("middle_id", middle_id);
              session.setAttribute("small_id", small_id);
              session.setAttribute("search_query", query);
              Statement objSql5=db.createStatement();
              ResultSet rs5=objSql5.executeQuery(query);
              while(rs5.next()){
            
      out.write("\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>");
      out.print(rs5.getString("bk_id"));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print(rs5.getString("bk_name"));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print(rs5.getString("writer"));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print(rs5.getString("pub_name"));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print(rs5.getDate("pub_date"));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print(rs5.getString("isbn_no"));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print(rs5.getInt("price"));
      out.write("</td>\r\n");
      out.write("                <td>");
if(rs5.getString("state").equals("true")){
      out.write("<button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\" ");
if((session.getAttribute("login") == null) || !session.getAttribute("login").equals("true")){
      out.write("disabled=disabled");
}
      out.write(" name=\"bk_id\" value=\"");
      out.print(rs5.getString("bk_id"));
      out.write("\" onClick=\"return confirm('");
      out.print(rs5.getString("bk_name"));
      out.write("を借りますか？')\">貸出可</button>");
}else{
      out.write("<button type=\"button\" class=\"btn btn-danger btn-lg btn-block\">貸出中</button>");
}
      out.write("</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            ");

            }
            rs5.close();
            objSql5.close();
            db.close();
            
      out.write("\r\n");
      out.write("          </table>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrapValidator.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    var wrapperSubmit = function(callObj) {\r\n");
      out.write("\r\n");
      out.write("      var large_id = document.getElementsByName('large_id');\r\n");
      out.write("      var middle_id = document.getElementsByName('middle_id');\r\n");
      out.write("      var small_id = document.getElementsByName('small_id');\r\n");
      out.write("      var large_id_is_not_checked = true;\r\n");
      out.write("      var middle_id_is_not_checked = true;\r\n");
      out.write("\r\n");
      out.write("      if (callObj.name == 'large_id') {\r\n");
      out.write("        for(var i=0; i < middle_id.length; i++)\r\n");
      out.write("        {\r\n");
      out.write("        middle_id[i].checked = false;\r\n");
      out.write("        }\r\n");
      out.write("        for(var i=0; i < small_id.length; i++)\r\n");
      out.write("        {\r\n");
      out.write("        small_id[i].checked = false;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("      if (callObj.name == 'middle_id') {\r\n");
      out.write("        for(var i=0; i < small_id.length; i++)\r\n");
      out.write("        {\r\n");
      out.write("        small_id[i].checked = false;\r\n");
      out.write("        }\r\n");
      out.write("        for(var i=0; i < large_id.length; i++)\r\n");
      out.write("        {\r\n");
      out.write("          if(large_id[i].checked == true)\r\n");
      out.write("          {\r\n");
      out.write("            large_id_is_not_checked = false;\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("        if(large_id_is_not_checked == true) {\r\n");
      out.write("          large_id[0].checked = true;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      if (callObj.name == 'small_id') {\r\n");
      out.write("        for(var i=0; i < large_id.length; i++)\r\n");
      out.write("        {\r\n");
      out.write("          if(large_id[i].checked == true)\r\n");
      out.write("          {\r\n");
      out.write("            large_id_is_not_checked = false;\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("        if(large_id_is_not_checked == true) {\r\n");
      out.write("          large_id[0].checked = true;\r\n");
      out.write("        }\r\n");
      out.write("        for(var i=0; i < middle_id.length; i++)\r\n");
      out.write("        {\r\n");
      out.write("          if(middle_id[i].checked == true)\r\n");
      out.write("          {\r\n");
      out.write("            middle_id_is_not_checked = false;\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("        if(middle_id_is_not_checked == true) {\r\n");
      out.write("          middle_id[0].checked = true;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      document.forms['search_form'].submit();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function clearAll() {\r\n");
      out.write("      var large_id = document.getElementsByName('large_id');\r\n");
      out.write("      var middle_id = document.getElementsByName('middle_id');\r\n");
      out.write("      var small_id = document.getElementsByName('small_id');\r\n");
      out.write("\r\n");
      out.write("      for(var i=0; i < large_id.length; i++)\r\n");
      out.write("        {\r\n");
      out.write("          large_id[i].checked = false;\r\n");
      out.write("        }\r\n");
      out.write("        for(var i=0; i < middle_id.length; i++)\r\n");
      out.write("        {\r\n");
      out.write("          middle_id[i].checked = false;\r\n");
      out.write("        }\r\n");
      out.write("        for(var i=0; i < small_id.length; i++)\r\n");
      out.write("        {\r\n");
      out.write("          small_id[i].checked = false;\r\n");
      out.write("        }\r\n");
      out.write("        document.forms['search_form'].submit();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $('.register_form').bootstrapValidator({\r\n");
      out.write("            live: 'disabled',\r\n");
      out.write("            message: 'This value is not valid',\r\n");
      out.write("            feedbackIcons: {\r\n");
      out.write("                valid: 'glyphicon glyphicon-ok',\r\n");
      out.write("                invalid: 'glyphicon glyphicon-remove',\r\n");
      out.write("                validating: 'glyphicon glyphicon-refresh'\r\n");
      out.write("            },\r\n");
      out.write("            fields: {\r\n");
      out.write("                register_id: {\r\n");
      out.write("                    message: 'ID is not valid',\r\n");
      out.write("                    validators: {\r\n");
      out.write("                        notEmpty: {\r\n");
      out.write("                            message: 'IDを入力してください'\r\n");
      out.write("                        },\r\n");
      out.write("                        stringLength: {\r\n");
      out.write("                            min: 4,\r\n");
      out.write("                            max: 4,\r\n");
      out.write("                            message: '有効なIDを入力してください'\r\n");
      out.write("                        },\r\n");
      out.write("                        integer: {\r\n");
      out.write("                            message: '半角数字で入力してください'\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                register_last_name: {\r\n");
      out.write("                    validators: {\r\n");
      out.write("                        notEmpty: {\r\n");
      out.write("                            message: 'お名前(姓)を入力してください'\r\n");
      out.write("                        },\r\n");
      out.write("                        stringLength: {\r\n");
      out.write("                            max: 20,\r\n");
      out.write("                            message: '全角10文字まで'\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                register_first_name: {\r\n");
      out.write("                    validators: {\r\n");
      out.write("                        notEmpty: {\r\n");
      out.write("                            message: 'お名前(名)を入力してください'\r\n");
      out.write("                        },\r\n");
      out.write("                        stringLength: {\r\n");
      out.write("                            max: 20,\r\n");
      out.write("                            message: '全角10文字まで'\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                register_email: {\r\n");
      out.write("                    validators: {\r\n");
      out.write("                        notEmpty: {\r\n");
      out.write("                            message: 'メールアドレスを入力してください'\r\n");
      out.write("                        },\r\n");
      out.write("                        emailAddress: {\r\n");
      out.write("                            message: '有効なメールアドレスを入力してください'\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                register_password: {\r\n");
      out.write("                    validators: {\r\n");
      out.write("                        notEmpty: {\r\n");
      out.write("                            message: 'パスワードを入力してください'\r\n");
      out.write("                        },\r\n");
      out.write("                        stringLength: {\r\n");
      out.write("                            min: 5,\r\n");
      out.write("                            max: 20,\r\n");
      out.write("                            message: '5 ～ 20文字で作成してください'\r\n");
      out.write("                        },\r\n");
      out.write("                        regexp: {\r\n");
      out.write("                            regexp: /(?=(.*[0-9])+|(.*[ !\\\"#$%&'()*+,\\-.\\/:;<=>?@\\[\\\\\\]^_`{|}~])+)(?=(.*[a-z])+)(?=(.*[A-Z])+)[0-9a-zA-Z !\\\"#$%&'()*+,\\-.\\/:;<=>?@\\[\\\\\\]^_`{|}~]{8,}/g,\r\n");
      out.write("                            message: '大文字、小文字、数字、ASCIIシンボルを含む半角の文字列で登録してください'\r\n");
      out.write("                        },\r\n");
      out.write("                        identical: {\r\n");
      out.write("                        field: 'confirm_register_password',\r\n");
      out.write("                        message: 'パスワードが一致しません'\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                confirm_register_password: {\r\n");
      out.write("                    validators: {\r\n");
      out.write("                        notEmpty: {\r\n");
      out.write("                            message: 'パスワードを再度入力してください'\r\n");
      out.write("                        },\r\n");
      out.write("                        stringLength: {\r\n");
      out.write("                            min: 5,\r\n");
      out.write("                            max: 20,\r\n");
      out.write("                            message: '5 ～ 20文字で作成してください'\r\n");
      out.write("                        },\r\n");
      out.write("                        regexp: {\r\n");
      out.write("                            regexp: /(?=(.*[0-9])+|(.*[ !\\\"#$%&'()*+,\\-.\\/:;<=>?@\\[\\\\\\]^_`{|}~])+)(?=(.*[a-z])+)(?=(.*[A-Z])+)[0-9a-zA-Z !\\\"#$%&'()*+,\\-.\\/:;<=>?@\\[\\\\\\]^_`{|}~]{8,}/g,\r\n");
      out.write("                            message: '大文字、小文字、数字、ASCIIシンボルを含む半角の文字列で登録してください'\r\n");
      out.write("                        },\r\n");
      out.write("                        identical: {\r\n");
      out.write("                        field: 'register_password',\r\n");
      out.write("                        message: 'パスワードが一致しません'\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('#myModal').on('shown.bs.modal', function() {\r\n");
      out.write("            $('.register_form').bootstrapValidator('resetForm', true);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function createPDF() {\r\n");
      out.write("      window.open(\"./CreatePDF\");\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
